import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header/Header";

// تعریف فونت یکان
const yekanFont = localFont({
  src: "./fonts/Yekan.woff",
  variable: "--font-yekan",
  // weight: "100 900", 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      {/* اعمال کلاس فونت به بادی */}
      <body className={`${yekanFont.variable} font-sans antialiased`}>
        {/* کانتینر مرکزی با عرض ۱۶۰۰ */}
        <div className="container mx-auto px-6 max-w-[1600px]">
          <Header /> 
          <main>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
